FROM golang:1.22-alpine AS builder
RUN apk add --no-cache git
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /test-backend ./cmd/test-backend/

FROM scratch
COPY --from=builder /test-backend /test-backend
EXPOSE 8080
ENTRYPOINT ["/test-backend"]
